version: '3.8'

services:
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_DB: EXAMPLE
      POSTGRES_USER: EXAMPLE
      POSTGRES_PASSWORD: EXAMPLE
    networks:
      - url-shortener-network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - url-shortener-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge
